name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      - 
        name: install dependencies
        run: sudo apt-get install pandoc texlive-xetex wkhtmltopdf
      -
        name: make pdf
        run: make cv.pdf
      -
        if: success() && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cv.pdf"
          tag: "v0.0.7"
          name: "PDF"
          body: "..."
          allowUpdates: true
      -
        if: github.ref != 'master'
        name: upload pdf
        uses: actions/upload-artifact@v4
        with: 
          name: cv.pdf
          path: cv.pdf
          retention-days: 1
          compression-level: 0
      -
        name: commit README
        run: |
          rm README.md
          make README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
            git commit -m "Update README"
            git push
          fi
